### ISSUE TITLE
Schedule FedoraObjectHarvester.new.harvest

### ISSUE THREAD

**Issue by jeremyf** [ndlib/hesburgh_metrics#23]
The existing `[FedoraObjectHarvester](https://github.com/ndlib/hesburgh_metrics/blob/master/app/services/fedora_object_harvester.rb)` needs to be scheduled to run with some frequency; I'm assuming at night.

- [ ] Setup a cronjob that can be run in the early morning and calls `FedoraObjectHarvester.new.harvest`
- [ ] Add a consideration for error handling
  - [ ] If we encounter an error on a single item, what do we do?
  - [ ] If there is a timeout error on the scheduled job, what do we do?

I'm assigning this to @laritakr but I believe @msuhovec has some guidance on how to wire this up.

**Comment by msuhovec** [comment]
@jfriesen @laritakr:

Is there a rake task for invoking FedoraObjectHarvester yet? Something like
https://github.com/ndlib/hesburgh_metrics/blob/master/lib/tasks/metrics.rake

I'd invoke this from a shell that checks a lock to insure it is not already
running, such as

https://github.com/vecnet/vecnet-dl/blob/master/script/sync_fedora_to_db.sh

or

https://github.com/ndlib/hesburgh_metrics/blob/master/script/harvest_metrics.sh

Then I'd configure Puppet to schedule a cronjob at the interval you's like.

**Comment by msuhovec** [comment]
did this against branch issue-24.  It's deployed to libvirt9
